allowBuilds:
  esbuild: true
  playwright-chromium: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  rollup: npm:rolldown@latest
overrides:
  esbuild: latest
  mermaid: latest
  monaco-editor: latest
  vite: 'catalog:'
  vitest: 'catalog:'
  rollup: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
shamefullyHoist: true
